### PR TITLE
fully implemented print-dir and print-hidden. Tested both successfully.

### PR DESCRIPTION
**Pull request by oliviacarino**
Ready to be merged into main. Fully tested and working. Will add error handling for non-existent directory when using the print-dir command in future commit before deadline.

### CODE REVIEW

**Comment by oliviacarino** [comment]
All merge conflicts fixed. @Snakeman57 I had to use my existing main() because I wasn't sure how you were combining it with the file IO, so you'll have to modify main() as well as handle_client(). I used Shubham's Codec wrapper but wasn't sure how your code would work combined with that.

Other than that, this is ready to merge within master with no conflicts.

**Comment by Snakeman57** [comment]
@oliviacarino if you want to see how my main is set up you can look at the matthew-sentell branch which has the updated version of it, file_sys, & the codec wrapper.

**Comment by oliviacarino** [comment]
@Snakeman57 Can you merge your changes into mine?

**Comment by mustakimur** [comment]
@oliviacarino @Snakeman57 @Shubham-Shingate @SivaNarayana1 I am not going to review anything before release v2 because it is too close to release and I don't want to blindly merge anything and take responsibility.

**Comment by oliviacarino** [comment]
Okay! One of us will merge it!
-------- Original message --------From: Mustakimur Rahman Khandaker ***@***.***> Date: 4/6/22  9:44 PM  (GMT-05:00) To: Shubham-Shingate/file-server ***@***.***> Cc: Olivia ***@***.***>, Mention ***@***.***> Subject: Re: [Shubham-Shingate/file-server] fully implemented print-dir and print-hidden. Tested both successfully. (PR #9) 
@oliviacarino @Snakeman57 @Shubham-Shingate @SivaNarayana1 I am not going to review anything before release v2 because it is too close to release and I don't want to blindly merge anything and take responsibility.

**Review by Snakeman57 — APPROVED** [review]
Approving for testing with Docker

**Pull request merged**
