### PR TITLE
Added notes for print directory command and print hidden files/directories.

### PR DESCRIPTION
**Pull request by oliviacarino**
Added notes for print directory command and print hidden files/directories. **I will personally move the logic from file-client for _these commands_ into file-server**

### CODE REVIEW

**Review by mustakimur — APPROVED** [review]
until it is close to release date, let allow everyone to test their feature how they want to.

**Comment by Shubham-Shingate** [comment]
> until it is close to release date, let allow everyone to test their feature how they want to.

Hello professor, as per our discussion yesterday I asked everyone to have a meeting. Siva provided his availability yesterday but Olivia and Matthew have not yet responded. The agenda of the meeting was on the same thing.

**Comment by oliviacarino** [comment]
> 

@Shubham-Shingate I would prefer if we discuss via text/email so there is a written reference.

**Comment by Shubham-Shingate** [comment]
Professor had suggested to keep a shared document and conduct a meeting (document will be shared to all team members as a written reference). I request you to ask professor about your preferences. Me and Siva are joining the meeting today to discuss concurrency related stuff. Anyone who wants to join can use the below link- 

Today 7:30 PM
meet.google.com/qcr-uerp-ucb

**Pull request merged**
